### PR TITLE
Use bigint for large numbers

### LINKED ISSUE #31: Deserialize integers beyond 53bits as bigint
```
import toml from 'smol-toml'
toml.parse('a=9223372036854775807')
```

Expected: `{ a: 9223372036854775807n }`

Seen: Exception (`Invalid TOML document: integer value cannot be represented losslessly`)

### PR DESCRIPTION
**Pull request by Gouvernathor**
Built on top of #40.
It is disabled by default. If the parse function is passed NUMBER_OR_ERROR directly (or if it is not passed an integer parsing option), the return type of the function will not include bigint, so it is backwards-compatible.
Fixes #31.

The new features are not covered by tests, but the existing tests (including internal unit tests) have been updated following general internal refactors.

### CODE REVIEW

File: src/primitive.ts [hunk 1]
```diff
@@ -126,51 +126,66 @@ export function parseString (str: string, ptr = 0, endPtr = str.length): string
 	return parsed + str.slice(sliceStart, endPtr - 1)
 }
 
-export function parseValue (value: string, toml: string, ptr: number): boolean | number | TomlDate {
+export enum IntegerParsing { NUMBER_OR_ERROR, NUMBER_OR_BIGINT, BIGINT_ONLY }
```
Comment (cyyynthia) [inline src/primitive.ts]: Exposed enums is kind of a footgun, as the TS output is relatively huge (and quite gross). I generally just use a string union, not the prettiest but it's the most straightforward.

Alternatively, it can be a `boolean | 'as_needed'`, which allows to treat false (`!integerParsingMode`) as "error on precision loss", and `integerParsingMode === true` to be "always bigint", where both do minify quite well.

File: src/primitive.ts [hunk 2]
```diff
@@ -126,51 +126,66 @@ export function parseString (str: string, ptr = 0, endPtr = str.length): string
...
+
+export function parseValue(value: string, toml: string, ptr: number, integerParsing: IntegerParsing = IntegerParsing.NUMBER_OR_ERROR): boolean | number | bigint | TomlDate {
```
Comment (cyyynthia) [inline src/primitive.ts]: Default value is not needed, this is an internal function.

File: src/primitive.ts [hunk 3]
```diff
@@ -126,51 +126,66 @@ export function parseString (str: string, ptr = 0, endPtr = str.length): string
...
-	if (value === 'inf' || value === '+inf') return Infinity
-	if (value === 'nan' || value === '+nan' || value === '-nan') return NaN
+	if (value === 'true') return true;
+	if (value === 'false') return false;
+	if (value === '-inf') return -Infinity;
+	if (value === 'inf' || value === '+inf') return Infinity;
+	if (value === 'nan' || value === '+nan' || value === '-nan') return NaN;
 
-	if (value === '-0') return 0 // Avoid FP representation of -0
+	if (value === '-0') return 0; // Avoid FP representation of -0
```
Comment (cyyynthia) [inline src/primitive.ts]: This path must not be taken when we always use bigints.

File: src/primitive.ts [hunk 4]
```diff
@@ -126,51 +126,66 @@ export function parseString (str: string, ptr = 0, endPtr = str.length): string
...
 
 	// Numbers
-	let isInt
-	if ((isInt = INT_REGEX.test(value)) || FLOAT_REGEX.test(value)) {
+	const isInt = INT_REGEX.test(value);
+	const isFloat = FLOAT_REGEX.test(value);
```
Comment (cyyynthia) [inline src/primitive.ts]: I use `let` because it's shorter than `const`, I think most if not all variables are `let` and not `const`.

Also, storing both is wasteful: given that we enter the branch only of it is an integer or a float, if `isInt` is false then you know it must be a floating point value. This is why it was written this way before, and I don't think modifying it is necessary at all.

File: src/primitive.ts [hunk 5]
```diff
@@ -126,51 +126,66 @@ export function parseString (str: string, ptr = 0, endPtr = str.length): string
...
+	if (isInt || isFloat) {
 		if (LEADING_ZERO.test(value)) {
 			throw new TomlError('leading zeroes are not allowed', {
 				toml: toml,
 				ptr: ptr
-			})
+			});
 		}
 
-		let numeric = +(value.replace(/_/g, ''))
```
Comment (cyyynthia) [inline src/primitive.ts:149]: The only special handling comes from integer values. So I think quite a lot can be simplified.

```ts
value = value.replace(...)
let numeric = +value
if (isNaN(value)) ...

if (isInt) {
  // isInt is no longer used, so we can reuse it to keep whether it's a safe int or not.
  if (!(isInt = Number.isSafeInteger(numeric)) && !useBigIntegers) ... // Precision loss.
  if (!isInt || useBigIntegers == 1) numeric = BigInt(value)
}
```

File: src/parse.ts [hunk 6]
```diff
@@ -113,10 +114,15 @@ function peekTable (key: string[], table: Record<string, TomlPrimitive>, meta: M
 	return [ k!, t, state.c ]
 }
 
-export function parse (toml: string, opts?: { maxDepth: number }): Record<string, TomlPrimitive> {
-	let maxDepth = opts?.maxDepth ?? 1000
-	let res = {}
-	let meta = {}
+export function parse(toml: string, options?: { maxDepth?: number }): TOMLTable<Exclude<TOMLPrimitive, bigint>>;
+export function parse(toml: string, options?: { maxDepth?: number, integerParsing: IntegerParsing.NUMBER_OR_ERROR }): TOMLTable<Exclude<TOMLPrimitive, bigint>>;
+export function parse(toml: string, options?: { maxDepth?: number, integerParsing: IntegerParsing }): TOMLTable;
```
Comment (cyyynthia) [inline src/parse.ts]: The generic options type can be exported as `ParseOptions`, and the overloads can be written with `ParseOptions & { integerParsing: ... }`

File: src/struct.ts [hunk 7]
```diff
@@ -116,8 +116,11 @@ export function parseKey (str: string, ptr: number, end = '='): [ string[], numb
 	return [ parsed, skipVoid(str, endPtr + 1, true, true) ]
 }
 
-export function parseInlineTable (str: string, ptr: number, depth: number = -1): [ Record<string, TomlPrimitive>, number ] {
-	let res: Record<string, TomlPrimitive> = {}
+export function parseInlineTable(
+	str: string, ptr: number,
+	{ depth = -1, integerParsing }: { depth?: number, integerParsing?: IntegerParsing|undefined } = {}
```
Comment (cyyynthia) [inline src/struct.ts]: !! objects as arguments are nice in some places, but very bad here as it prevents minifiers from making everything a single-letter variable. Getting rid of the -1 default would be ideal :/

**Review by cyyynthia — CHANGES_REQUESTED** [review]
Thanks for the PR! Stylistic nits mentioned in #40 apply - please try to keep the original code style intact (I know, no formatter, annoying, sorry!) 🙂

File: src/primitive.ts (hunk 1 above)
Comment (Gouvernathor) [reply src/primitive.ts]: I like how string unions are supported by Typescript. It's also clearer to use from javascript, and I don't like boolean-or-else types : for me a boolean is meant to be binary.

File: src/primitive.ts (hunk 4 above)
Comment (Gouvernathor) [reply src/primitive.ts]: It's not wasteful because I use it in another if. (I wouldn't waste a variable otherwise, I agree.) But it may disappear in another refacto.

File: src/primitive.ts (hunk 2 above)
Comment (Gouvernathor) [reply src/primitive.ts]: The issue is that it makes the unit tests more verbose, since in that case all functions except for parse will need the parameter to be passed. Is that what you want ?

File: src/struct.ts (hunk 7 above)
Comment (Gouvernathor) [reply src/struct.ts]: Except for exceptionally stable interfaces (such as string.substring for instance), I think all optional parameters should be in keyword option parameters.
But even short of that, I think positional-only parameters are bad as soon as two independent parameters are optional - as was visible from the use of `void 0` somewhere (maybe in tests) to skip a parameter.
We can make depth required and integerParsing the only optional, but the same problem would bite us back as soon as the next option is implemented...

File: src/primitive.ts (hunk 2 above)
Comment (cyyynthia) [reply src/primitive.ts]: Yeah, at least the tests will be explicit about what's the precise thing being tested. Better to have the extra weight in the tests rather than in production bundles :)

File: src/struct.ts (hunk 7 above)
Comment (cyyynthia) [reply src/struct.ts]: Those functions are internal and won't ever be exposed to public-facing APIs, and the code is small enough that dealing with interfaces changing is a non-issue. The code size impact does matter a lot to me. It must be *smol*.

All parameters can be marked as required, again since it's internal and the fact they're optional is only something the user sees in the public APIs.

Comment (Gouvernathor) [reply src/struct.ts]: extractValue's `end` parameter is now required with undefined being allowed, which is slightly regrettable but better than putting it away from ptr.

File: src/primitive.ts (hunk 3 above)
Comment (Gouvernathor) [reply src/primitive.ts]: Done, but how about `-0.0` ? That's not handled, is it ?

File: src/primitive.ts (hunk 2 above)
Comment (Gouvernathor) [reply src/primitive.ts]: Done

File: src/parse.ts (hunk 6 above)
Comment (Gouvernathor) [reply src/parse.ts]: The first overload can't be expressed like this - or I don't know how

File: src/primitive.ts (hunk 3 above)
Comment (Gouvernathor) [reply src/primitive.ts]: In fact there's even a test that "-0.0" returns the negative zero. Shouldn't that be fixed so that "-0" always returns the same thing as "-0.0" ?

File: src/primitive.ts (hunk 5 above)
Comment (Gouvernathor) [reply src/primitive.ts:149]: We don't even need to reuse the variable, actually (I do frown upon that)

File: src/primitive.ts (hunk 4 above)
Comment (Gouvernathor) [reply src/primitive.ts]: Done

File: src/primitive.ts (hunk 3 above)
Comment (cyyynthia) [reply src/primitive.ts]: This special case was done so that `-0`, `0`, and `+0` are strictly equal to `0`. This is generally intended, and explicitly specified by the specification: https://toml.io/en/v1.0.0#integer

While the floating point `-0.0` is equal to `0.0` per IEEE 754, its behavior differs in some edge-cases. They're equal (`-0 === 0` is true), but not strictly equal (`Object.is(-0, 0)` is false, `1/0` is Infinity but `1/-0` is -Infinity). So, since `-0` would get parsed as a float, there needs to be a special case for it such that it does return exactly `0`.

File: src/parse.ts (hunk 6 above)
Comment (cyyynthia) [reply src/parse.ts]: The order of the overloads matter. [TypeScript playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBA8mwEsD2A7AzlAvFA3gKCkKgEMB+ALijWACcEUBzAogIwqhaSQBsJiU8AXzx4AZgFcUAY0SooAEyQBlJAFsIwABb0GUABTFKcWeigAyXB0q1x0QQEpKABjGSZyFAuVqN2xvsNYeA8MCxwrKFFibjQ7RygARldpEy8VdS0dAKNg1DR4lHFVFggaZPc5RXTfLIMck3zKQuLS3GZCGg1xGk8ATiERKTzgEiw0n0zGPRwHPAB6OaIoAD1SPCH0EZYxqom-BmmImzj5xaJV9eGoKR3vDP3DlkoomJOFpYugA)

File: src/primitive.ts (hunk 4 above)
Comment (cyyynthia) [reply src/primitive.ts]: My point is that if you know `isInt`, then you necessarily know `isFloat` when you're inside the numeric processing logic. `isFloat === !isInt`, so there's no need to store it alongside `isInt`

File: src/primitive.ts (hunk 1 above)
Comment (cyyynthia) [reply src/primitive.ts]: Sometimes they're expressive enough... I agree as a type theorist (using an enum is the proper solution, string union is a poor man's enum so it's equally acceptable), but as a TS dev optimizing for code-size... The fact undefined is falsey allows for neat optimization tricks 🤷🏻‍♀️

File: src/parse.ts (hunk 6 above)
Comment (Gouvernathor) [reply src/parse.ts]: Is this what you have in mind ?
```ts
export function parse (toml: string, options?: ParseOptions & { integerParsing: "number_or_error" }): TomlTable<Exclude<TomlPrimitive, bigint>>;
export function parse (toml: string, options?: ParseOptions & { integerParsing: IntegerParsing }): TomlTable;
export function parse (toml: string, options?: ParseOptions): TomlTable<Exclude<TomlPrimitive, bigint>>;
```
I don't find it very readable personally.

Comment (cyyynthia) [reply src/parse.ts]: Hm, it can be done in 2 overloads only, i.e.

```ts
export function parse (toml: string, options?: ParseOptions & { integerParsing: Exclude<IntegerParsing, 'number_or_error'> }): TomlTable
export function parse (toml: string, options?: ParseOptions): TomlTable<Exclude<TomlPrimitive, bigint>>
```

It's not ideal, but as `ParseOptions` will eventually grow it'll become even more of a pain. Intersected type could be hoisted, i.e.

```ts
type TomlTable = { [key: string]: ... }
type TomlTableWithBigint = { [key: string]: bigint | ... }

// ---

type ParseOptionsWithBigInt = ParseOptions & { integerParsing: Exclude<IntegerParsing, 'number_or_error'>

export function parse (toml: string, options?: ParseOptionsWithBigInt): TomlTableWithBigInt
export function parse (toml: string, options?: ParseOptions): TomlTable
export function parse (toml: string, options?: ParseOptions): TomlTableWithBigInt {
  ...
}
```

File: src/primitive.ts (hunk 3 above)
Comment (Gouvernathor) [reply src/primitive.ts]: I'm adding a test for that.

File: src/primitive.ts (hunk 5 above)
Comment (cyyynthia) [reply src/primitive.ts:149]: Yeah I'd frown upon that in most other situations too. Again, here I'm in the shoes of someone optimizing for code size, and sometimes sacrifices needs to be made. It's not *too* bad either, as the type remains the same at least. 🤷🏻‍♀️

I'm sure you've seen worse in the code already, I used some very cursed tricks here and there 😅

File: src/parse.ts (hunk 6 above)
Comment (Gouvernathor) [reply src/parse.ts]: I did it the first way. I don't generally like single-use definitions.

File: src/primitive.ts (hunk 5 above)
Comment (Gouvernathor) [reply src/primitive.ts:149]: TODO : I think that version doesn't support numbers over e310, since once converted to number they are nan but yet they may be integers supported by bigint.
There needs to be a test about that too.

Comment (cyyynthia) [reply src/primitive.ts:149]: `1e1` forms are floating point numbers, never integers. https://toml.io/en/v1.0.0#float

Comment (Gouvernathor) [reply src/primitive.ts:149]: I meant higher than that value, they can be written as a string of 300+ digits

Comment (cyyynthia) [reply src/primitive.ts:149]: Are you sure they get converted to NaN? I get Infinity after a quick test, which is fine (it's not NaN, and it's not a safe integer either) 🤔 

```
Node REPL
> +('9'.repeat(310))
Infinity
```

Comment (Gouvernathor) [reply src/primitive.ts:149]: I added tests for that.

**Comment by Gouvernathor** [comment]
This, in the readme 

> floats will be serialized as integers if they don't have a decimal part. `stringify(parse('a = 1.0')) === 'a = 1'`

could be disabled in an option on the stringify function, to serialize all numbers as floats, and it would mirror the integers_as_bigint option on parse. That way, you could have type-stable parse-serialization cycles.

File: test/value.test.ts [hunk 8]
```diff
@@ -32,149 +32,172 @@ import { TomlError } from '../src/error.js'
...
 
-it('rejects numbers too large', () => {
-	expect(() => parseValue('9007199254740992', '', 0)).toThrowError(TomlError)
+it('rejects numbers too large on number_or_error', () => {
+	expect(() => parseValue('9007199254740992', '', 0, "number_or_error")).toThrowError(TomlError)
+})
+
+it('supports numbers larger than the max safe integer number when bigints are enabled', () => {
+	expect(parseValue('9007199254740992', '', 0, "number_or_bigint")).toBe(BigInt('9007199254740992'))
+	expect(parseValue('9007199254740992', '', 0, "integers_as_bigints")).toBe(BigInt('9007199254740992'))
```
Comment (cyyynthia) [inline test/value.test.ts]: Style: expected bigint could be written using `0n` syntax instead

**Review by cyyynthia — COMMENTED** [review]
I have stylistic nits, but nothing too important. I only annotated one but I could also mention the presence of semicolons etc. Tests look good, I'll probably change a few things in the implementation before release but the core logic seems good.

You don't necessarily need to fix style issues, I can handle that myself before merging. I'll squash and merge PRs, so they'll need to be rebased once I start merging things.

**Review by cyyynthia — APPROVED** [review]
